add install libjpeg8-dev for mjpg_streamer

diff --git a/install_dependencies b/install_dependencies
--- a/install_dependencies
+++ b/install_dependencies
@@ -13,6 +13,7 @@ repo_dir=`pwd`
 is_installed_django=False
 is_installed_python_smbus=False
 is_installed_python_opencv=False
+is_installed_libjpeg8-dev=False
 
 if [ "$(whoami)" != "root" ] ; then
     echo -e "You must run this script as root."
@@ -53,15 +54,18 @@ function print_result(){
     fi
     echo -e "python-smbus  \c"
     if $is_installed_python_smbus; then
-<<<<<<< HEAD
-=======
         echo -e "Success"
     else
         echo -e "Failed"
     fi
     echo -e "python-opencv  \c"
     if $is_installed_python_opencv; then
->>>>>>> eb785ba4dbc563cb14c05c6eeaa675107dd139ac
+        echo -e "Success"
+    else
+        echo -e "Failed"
+    fi
+    echo -e "libjpeg8-dev  \c"
+    if $is_installed_libjpeg8-dev; then
         echo -e "Success"
     else
         echo -e "Failed"
@@ -96,8 +100,6 @@ else
     if_continue
     if [ $? = 1 ] ; then
         echo -e "    Skipped python-smbus installation."
-<<<<<<< HEAD
-=======
     else
         end
     fi
@@ -113,7 +115,21 @@ else
     if_continue
     if [ $? = 1 ] ; then
         echo -e "    Skipped python-opencv installation."
->>>>>>> eb785ba4dbc563cb14c05c6eeaa675107dd139ac
+    else
+        end
+    fi
+fi
+
+echo -e "\nInstalling libjpeg8-dev \n"
+if sudo apt-get install libjpeg8-dev -y; then
+    echo -e "    Successfully installed libjpeg8-dev \n"
+    is_installed_libjpeg8-dev=true
+else
+    echo -e "    Failed to installed libjpeg8-dev \n"
+    echo -e "    Do you want to skip this? \c"
+    if_continue
+    if [ $? = 1 ] ; then
+        echo -e "    Skipped libjpeg8-dev installation."
     else
         end
     fi
