Update install_dependencies

diff --git a/install_dependencies b/install_dependencies
--- a/install_dependencies
+++ b/install_dependencies
@@ -64,12 +64,12 @@ function print_result(){
     else
         echo -e "Failed"
     fi
-    echo -e "libjpeg8-dev  \c"
-    if $is_installed_libjpeg8_dev; then
-        echo -e "Success"
-    else
-        echo -e "Failed"
-    fi
+#     echo -e "libjpeg8-dev  \c"
+#     if $is_installed_libjpeg8_dev; then
+#         echo -e "Success"
+#     else
+#         echo -e "Failed"
+#     fi
 }
 
 ###################################
@@ -120,20 +120,20 @@ else
     fi
 fi
 
-echo -e "\nInstalling libjpeg8-dev \n"
-if sudo apt-get install libjpeg8-dev -y; then
-    echo -e "    Successfully installed libjpeg8-dev \n"
-    is_installed_libjpeg8_dev=true
-else
-    echo -e "    Failed to installed libjpeg8-dev \n"
-    echo -e "    Do you want to skip this? \c"
-    if_continue
-    if [ $? = 1 ] ; then
-        echo -e "    Skipped libjpeg8-dev installation."
-    else
-        end
-    fi
-fi
+# echo -e "\nInstalling libjpeg8-dev \n"
+# if sudo apt-get install libjpeg8-dev -y; then
+#     echo -e "    Successfully installed libjpeg8-dev \n"
+#     is_installed_libjpeg8_dev=true
+# else
+#     echo -e "    Failed to installed libjpeg8-dev \n"
+#     echo -e "    Do you want to skip this? \c"
+#     if_continue
+#     if [ $? = 1 ] ; then
+#         echo -e "    Skipped libjpeg8-dev installation."
+#     else
+#         end
+#     fi
+# fi
 
 ###################################
 # Install RPi Car V2 Module
